apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberhaus-deployment
  namespace: kube-system
  labels:
    app: kuberhaus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuberhaus
  template:
    metadata:
      labels:
        app: kuberhaus
    spec:
      serviceAccountName: cluster-admin
      containers:
      - name: kuberhaus
        image: stevelacy/kuberhaus:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8282
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cluster-admin
  namespace: kube-system