# ❯ helm install openebs-nfs openebs-nfs/nfs-provisioner --namespace openebs --create-namespace
# ❯ helm repo add openebs-nfs https://openebs.github.io/dynamic-nfs-provisioner
apiVersion: v1
kind: Namespace
metadata:
  name: storage
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs-provisioner
  namespace: kube-system
spec:
  repo: https://openebs.github.io/dynamic-nfs-provisioner
  chart: nfs-provisioner
  targetNamespace: storage
  valuesContent: |-
#     extraArgs:
#       - --enable-skip-login
#       - --enable-insecure-login
#       - --system-banner="Welcome to Kubernetes"
#     protocolHttp: true
#     service:
#       externalPort: 8080
#     ingress:
#       enabled: true
#       hosts:
#         - dash.localtest.me
#       tls:
#         - hosts:
#             - dash.localtest.me
#     metricsScraper:
#       enabled: true

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: kubernetes-dashboard
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cluster-admin
# subjects:
# - kind: ServiceAccount
#   name: kubernetes-dashboard
#   namespace: kubernetes-dashboard
