---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  # selector:
  #   matchLabels:
  #     pv: local
  storageClassName: openebs-kernel-nfs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  # selector:
  #   matchLabels:
  #     pv: local
  storageClassName: openebs-kernel-nfs