{{ if .Values.global.weavescope.enabled }}
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: storage
# ---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: weave-scope
  namespace: kube-system
spec:
  repo: https://cloudnativeapp.github.io/charts/curated/
  chart: weave-scope
  targetNamespace: default
  valuesContent: |-
    ingress:
      enabled: true
      hosts:
        - weave.{{ .Values.global.domain }}
      tls: 
       - hosts:
           - weave.{{ .Values.global.domain }}
    # consoleIngress:
    #   enabled: true
    #   hosts:
    #     - minio.{{ .Values.global.domain }}
    #   tls: 
    #    - hosts:
    #        - minio.{{ .Values.global.domain }}
    # users:
    #   - accessKey: console
    #     secretKey: console123
    #     policy: consoleAdmin
    # buckets:
    #   - name: default
    #     policy: public
    #     purge: true
    # environment:
    #   MINIO_PROMETHEUS_URL: "http://prometheus-server.monitoring"
    #   MINIO_PROMETHEUS_JOB_ID: kubernetes-pods
    # podAnnotations:
    #   prometheus.io/path: /minio/v2/metrics/cluster
    #   prometheus.io/port: "9000"
    #   prometheus.io/scrape: "true"
{{- end }}
